/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIAgentSettings: typeof import('./src/components/settings/AIAgentSettings.vue')['default']
    AppearanceSettings: typeof import('./src/components/settings/AppearanceSettings.vue')['default']
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    Badge: typeof import('./src/components/ui/Badge.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    ColorPicker: typeof import('./src/components/ui/ColorPicker.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CustomThemeEditor: typeof import('./src/components/settings/CustomThemeEditor.vue')['default']
    Dialog: typeof import('./src/components/ui/Dialog.vue')['default']
    DialogDescription: typeof import('./src/components/ui/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/ui/DialogTitle.vue')['default']
    DropdownMenu: typeof import('./src/components/ui/DropdownMenu.vue')['default']
    DropdownMenuItem: typeof import('./src/components/ui/DropdownMenuItem.vue')['default']
    DropdownMenuSeparator: typeof import('./src/components/ui/DropdownMenuSeparator.vue')['default']
    EditorSettings: typeof import('./src/components/settings/EditorSettings.vue')['default']
    FileOperationModal: typeof import('./src/components/FileOperationModal.vue')['default']
    FileTreeNode: typeof import('./src/components/FileTreeNode.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    Label: typeof import('./src/components/ui/Label.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    Progress: typeof import('./src/components/ui/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ui/ScrollArea.vue')['default']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    Separator: typeof import('./src/components/ui/Separator.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    Skeleton: typeof import('./src/components/ui/Skeleton.vue')['default']
    Table: typeof import('./src/components/ui/Table.vue')['default']
    TableBody: typeof import('./src/components/ui/TableBody.vue')['default']
    TableCell: typeof import('./src/components/ui/TableCell.vue')['default']
    TableHead: typeof import('./src/components/ui/TableHead.vue')['default']
    TableHeader: typeof import('./src/components/ui/TableHeader.vue')['default']
    TableRow: typeof import('./src/components/ui/TableRow.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/TabsContent.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/TabsTrigger.vue')['default']
    TerminalPane: typeof import('./src/components/TerminalPane.vue')['default']
    TerminalSettings: typeof import('./src/components/settings/TerminalSettings.vue')['default']
    Textarea: typeof import('./src/components/ui/Textarea.vue')['default']
    ThinkingBlock: typeof import('./src/components/ai/ThinkingBlock.vue')['default']
    ToolApprovalCard: typeof import('./src/components/ai/ToolApprovalCard.vue')['default']
    ToolBlock: typeof import('./src/components/ai/ToolBlock.vue')['default']
    ToolCallCard: typeof import('./src/components/ai/ToolCallCard.vue')['default']
    ToolResultCard: typeof import('./src/components/ai/ToolResultCard.vue')['default']
    Tooltip: typeof import('./src/components/ui/Tooltip.vue')['default']
    UsageRing: typeof import('./src/components/UsageRing.vue')['default']
  }
}
