apiVersion: v1
kind: Secret
metadata:
  name: webide-backend-secret
  namespace: webide
type: Opaque
stringData:
  IDE_DATA_DIR: /app/data
  IDE_PROJECTS_DIR: /app/projects
  IDE_HTTP_ADDR: ":8080"
  IDE_SESSION_TTL_HOURS: "168"
  IDE_USER_BOOTSTRAP_EMAIL: admin@sviniabanditka.com
  IDE_USER_BOOTSTRAP_PASSWORD: WebIde_Prod_2024
